#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""Generate Pareto frontier TikZ figure for the paper.

Reads: data/results_all.csv
Outputs: Prints TikZ code for figures/pareto.tex

Usage:
    python generate_pareto.py > ../figures/pareto.tex
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import *


def main():
    rows = load_results()
    base = [r for r in rows if r["has_unsafe_tool"]]

    grouped = defaultdict(list)
    for r in base:
        key = (r["model_ids"], r["platform"], r["task_type"])
        grouped[key].append(r)

    coords = {}
    for model in PAPER_MODELS:
        for platform in ["desktop", "mobile"]:
            b_key = (model, platform, "benign")
            m_key = (model, platform, "malicious")
            if b_key in grouped and m_key in grouped:
                tsr = statistics.mean([float(r["score"]) for r in grouped[b_key]]) * 100
                safety = (
                    1 - statistics.mean([float(r["score"]) for r in grouped[m_key]])
                ) * 100
                coords[(model, platform)] = (tsr, safety)

    markers = {
        "gemini-3.1-pro": ("o", "teal!80", 5),
        "claude-4.7-opus": ("square*", "violet!80", 5),
        "gpt-5.4": ("triangle*", "red!70", 5),
        "gemini-2.5-cu": ("*", "teal!80", 5),
        "qwen3-vl-235b": ("diamond*", "orange!80", 5),
        "qwen3-vl-8b": ("diamond", "orange!80", 5),
        "qwen3-vl-4b": ("diamond*", "orange!50", 4),
    }

    label_names = {
        "gemini-3.1-pro": "Gemini 3.1",
        "claude-4.7-opus": "Claude 4.7",
        "gpt-5.4": "GPT-5.4",
        "gemini-2.5-cu": "Gemini CU",
        "qwen3-vl-235b": "Q-235B",
        "qwen3-vl-8b": "Q-8B",
        "qwen3-vl-4b": "Q-4B",
    }

    for platform in ["mobile", "desktop"]:
        n = EXPECTED_N[platform]
        title = f"\\textbf{{{platform.title()}}} ($n$={n})"

        print(f"% Pareto: {platform}")
        print("\\begin{tikzpicture}")
        print("\\begin{axis}[")
        print("    width=0.48\\textwidth, height=0.4\\textwidth,")
        print("    xlabel={TSR (\\%, higher = more capable)},")
        print("    ylabel={$1{-}\\text{ASR}$ (\\%, higher = safer)},")
        print("    xmin=55, xmax=90, ymin=15, ymax=80,")
        print("    grid=both, grid style={gray!20},")
        print(f"    title={{{title}}},")
        print("    title style={font=\\small\\sffamily},")
        print("    xlabel style={font=\\small}, ylabel style={font=\\small},")
        print("    tick label style={font=\\tiny},")
        print("]")

        print(
            "\\draw[gray!30, dashed, thick] (axis cs:75,70) rectangle (axis cs:90,80);"
        )
        print("\\node[font=\\tiny\\sffamily, gray!50] at (axis cs:82.5,75) {Ideal};")

        for model in PAPER_MODELS:
            if (model, platform) not in coords:
                continue
            tsr, safety = coords[(model, platform)]
            mark, color, size = markers[model]
            label = label_names[model]

            print(
                f"\\addplot[only marks, mark={mark}, mark size={size}pt, {color}] coordinates {{({tsr:.1f}, {safety:.1f})}};"
            )
            print(
                f"\\node[font=\\tiny\\sffamily\\bfseries, {color}, above right] at (axis cs:{tsr:.1f},{safety:.1f}) {{{label}}};"
            )

        print("\\end{axis}")
        print("\\end{tikzpicture}")
        if platform == "mobile":
            print("\\hfill")

    print(
        "\n% Generated by generate_pareto.py — update coordinates from main_results_10run.py"
    )


if __name__ == "__main__":
    main()
